{% set name = "pygenomeviz" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygenomeviz-{{ version }}.tar.gz
  sha256: bedfe310000d8264c7f5cd027a8bb17b7f5ed49b500a0b4c6d6520f0dcc32710

build:
  entry_points:
    - pgv-blast = pygenomeviz.scripts.blast:main
    - pgv-mummer = pygenomeviz.scripts.mummer:main
    - pgv-mmseqs = pygenomeviz.scripts.mmseqs:main
    - pgv-pmauve = pygenomeviz.scripts.pmauve:main
    - pgv-download = pygenomeviz.scripts.download:main
    - pgv-gui = pygenomeviz.scripts.gui:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - matplotlib-base >=3.6.3
    - biopython >=1.80
    - numpy >=1.21
  run_constrained:
    - streamlit >=1.32.0

test:
  imports:
    - pygenomeviz
  commands:
    - pip check
    - pgv-blast --help
    - pgv-mummer --help
    - pgv-mmseqs --help
    - pgv-pmauve --help
    - pgv-download --help
    - pgv-gui --help
  requires:
    - pip

about:
  home: https://github.com/moshi4/pyGenomeViz/
  summary: A genome visualization python package for comparative genomics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moshi4
